
apiVersion: apps/v1
kind: Deployment
metadata:
  name: testnet-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testnet
  template:
    metadata:
      labels:
        app: testnet
    spec:
      containers:
      - name: fullnode
        image: '984706561510.dkr.ecr.us-east-2.amazonaws.com/0l_fullnode:latest'
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        command: ["libra-node"]
        args: ["--config", "/root/.0L/fullnode.node.yaml"]